// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
	vec3 ka, kd, n, v, l;
    vec3 ks = vec3(1, 1, 1);
    float p = 1000;
    float noise;

    if (is_moon) {
        ka = vec3(0.05, 0.05, 0.05);
        kd = vec3(0.5, 0.45, 0.45);
        noise = abs(sin(cos(perlin_noise(sphere_fs_in) * 22) * 3));
    } else {
        ka = vec3(0.02, 0.02, 0.08);
        kd = vec3(0.2, 0.2, 0.8);
        noise = abs(cos(sin(perlin_noise(sphere_fs_in) * 33) / 2));
    }

    vec4 light_d = view * vec4(4 * cos(M_PI * animation_seconds / 4), 2.5, 4 * sin(M_PI * animation_seconds / 4), 1);
    n = normalize(normal_fs_in);
    v = normalize(-view_pos_fs_in).xyz;
    l = normalize(light_d - view_pos_fs_in).xyz;

    color = blinn_phong(ka, kd * noise, ks, p, n, v, l);
}
